### ISSUE TITLE
Slc S32053

### ISSUE THREAD

**Issue by JohnIvarB** [easyhomesrc/Homey_SLC_SmartOne_Issues#2]
Hi, is there any chance to include S32053 into the slc app for homey?

**Comment by maginawin** [comment]
Hi @JohnIvarB ,

We support S32053 on Homey v5. The attachment describes how to upgrade Homey to v5.
[Guidelines update Homey Gateway to v5.pdf](https://github.com/easyhomesrc/Homey_SLC_SmartOne_Issues/files/5665074/Guidelines.update.Homey.Gateway.to.v5.pdf)

Test App 
https://homey.app/a/com.matcallbv.matcall/test/
